import { writable } from "svelte/store";

export const localeCodes = [
  "zh-CN",
  "zh-TW",
  "en",
  "ja",
  "ko",
  "fr",
  "de",
  "es",
  "pt",
  "ru",
  "ar"
] as const;

export type LocaleCode = (typeof localeCodes)[number];
type MessageParams = Record<string, string | number>;
type MessageRow = readonly [string, ...string[]];

export const localeOptions: ReadonlyArray<{ code: LocaleCode; nativeName: string; dir: "ltr" | "rtl" }> = [
  { code: "zh-CN", nativeName: "简体中文", dir: "ltr" },
  { code: "zh-TW", nativeName: "繁體中文", dir: "ltr" },
  { code: "en", nativeName: "English", dir: "ltr" },
  { code: "ja", nativeName: "日本語", dir: "ltr" },
  { code: "ko", nativeName: "한국어", dir: "ltr" },
  { code: "fr", nativeName: "Français", dir: "ltr" },
  { code: "de", nativeName: "Deutsch", dir: "ltr" },
  { code: "es", nativeName: "Español", dir: "ltr" },
  { code: "pt", nativeName: "Português", dir: "ltr" },
  { code: "ru", nativeName: "Русский", dir: "ltr" },
  { code: "ar", nativeName: "العربية", dir: "rtl" }
];

// Key, zh-CN, zh-TW, en, ja, ko, fr, de, es, pt, ru, ar.
const rows: MessageRow[] = [
  ["app.title", "灵栈 · Agent & Skill 管理器", "靈棧 · Agent & Skill 管理器", "Lingzhan · Agent & Skill Manager", "Lingzhan · Agent & Skill マネージャー", "Lingzhan · Agent & Skill 관리자", "Lingzhan · Gestionnaire Agent & Skill", "Lingzhan · Agent-&-Skill-Manager", "Lingzhan · Gestor de Agent y Skill", "Lingzhan · Gestor de Agent e Skill", "Lingzhan · Менеджер Agent & Skill", "Lingzhan · مدير Agent وSkill"],
  ["app.brand", "灵栈", "靈棧", "Lingzhan", "Lingzhan", "Lingzhan", "Lingzhan", "Lingzhan", "Lingzhan", "Lingzhan", "Lingzhan", "Lingzhan"],
  ["language.label", "界面语言", "介面語言", "Interface language", "表示言語", "인터페이스 언어", "Langue de l’interface", "Oberflächensprache", "Idioma de la interfaz", "Idioma da interface", "Язык интерфейса", "لغة الواجهة"],
  ["nav.workbench", "工作台", "工作台", "Workbench", "ワークベンチ", "작업 공간", "Espace de travail", "Arbeitsbereich", "Espacio de trabajo", "Área de trabalho", "Рабочая область", "مساحة العمل"],
  ["nav.overview", "总览", "總覽", "Overview", "概要", "개요", "Vue d’ensemble", "Übersicht", "Resumen", "Visão geral", "Обзор", "نظرة عامة"],
  ["nav.assets", "全部资产", "全部資產", "All assets", "すべてのアセット", "모든 자산", "Tous les actifs", "Alle Assets", "Todos los activos", "Todos os ativos", "Все ресурсы", "كل الأصول"],
  ["nav.projects", "项目地图", "專案地圖", "Project map", "プロジェクトマップ", "프로젝트 맵", "Carte des projets", "Projektkarte", "Mapa de proyectos", "Mapa de projetos", "Карта проектов", "خريطة المشاريع"],
  ["nav.evolution", "版本与优化", "版本與優化", "Versions & optimization", "バージョンと最適化", "버전 및 최적화", "Versions et optimisation", "Versionen & Optimierung", "Versiones y optimización", "Versões e otimização", "Версии и оптимизация", "الإصدارات والتحسين"],
  ["nav.controls", "统一控制", "統一控制", "Unified control", "統合コントロール", "통합 제어", "Contrôle unifié", "Einheitliche Steuerung", "Control unificado", "Controle unificado", "Единое управление", "التحكم الموحد"],
  ["nav.exports", "导出中心", "匯出中心", "Export center", "エクスポートセンター", "내보내기 센터", "Centre d’export", "Exportzentrum", "Centro de exportación", "Central de exportação", "Центр экспорта", "مركز التصدير"],
  ["common.close", "关闭", "關閉", "Close", "閉じる", "닫기", "Fermer", "Schließen", "Cerrar", "Fechar", "Закрыть", "إغلاق"],
  ["common.cancel", "取消", "取消", "Cancel", "キャンセル", "취소", "Annuler", "Abbrechen", "Cancelar", "Cancelar", "Отмена", "إلغاء"],
  ["common.save", "保存", "儲存", "Save", "保存", "저장", "Enregistrer", "Speichern", "Guardar", "Salvar", "Сохранить", "حفظ"],
  ["common.edit", "编辑", "編輯", "Edit", "編集", "편집", "Modifier", "Bearbeiten", "Editar", "Editar", "Изменить", "تحرير"],
  ["common.delete", "删除", "刪除", "Delete", "削除", "삭제", "Supprimer", "Löschen", "Eliminar", "Excluir", "Удалить", "حذف"],
  ["common.refresh", "刷新", "重新整理", "Refresh", "更新", "새로 고침", "Actualiser", "Aktualisieren", "Actualizar", "Atualizar", "Обновить", "تحديث"],
  ["common.loading", "正在加载…", "正在載入…", "Loading…", "読み込み中…", "로드 중…", "Chargement…", "Wird geladen…", "Cargando…", "Carregando…", "Загрузка…", "جارٍ التحميل…"],
  ["common.all", "全部", "全部", "All", "すべて", "전체", "Tout", "Alle", "Todo", "Todos", "Все", "الكل"],
  ["common.none", "无", "無", "None", "なし", "없음", "Aucun", "Keine", "Ninguno", "Nenhum", "Нет", "لا شيء"],
  ["common.notLoaded", "未载入", "未載入", "Not loaded", "未読み込み", "로드되지 않음", "Non chargé", "Nicht geladen", "Sin cargar", "Não carregado", "Не загружено", "غير محمّل"],
  ["common.viewAll", "查看全部", "查看全部", "View all", "すべて表示", "모두 보기", "Tout afficher", "Alle anzeigen", "Ver todo", "Ver tudo", "Показать все", "عرض الكل"],
  ["common.search", "搜索", "搜尋", "Search", "検索", "검색", "Rechercher", "Suchen", "Buscar", "Pesquisar", "Поиск", "بحث"],
  ["common.clear", "清除", "清除", "Clear", "クリア", "지우기", "Effacer", "Leeren", "Limpiar", "Limpar", "Очистить", "مسح"],
  ["common.reset", "重置", "重設", "Reset", "リセット", "초기화", "Réinitialiser", "Zurücksetzen", "Restablecer", "Redefinir", "Сбросить", "إعادة ضبط"],
  ["common.selected", "已选择", "已選擇", "selected", "選択済み", "선택됨", "sélectionné(s)", "ausgewählt", "seleccionado(s)", "selecionado(s)", "выбрано", "محدد"],
  ["common.items", "{count} 项", "{count} 項", "{count} items", "{count} 件", "{count}개", "{count} éléments", "{count} Elemente", "{count} elementos", "{count} itens", "{count} элем.", "{count} عنصر"],
  ["common.page", "第 {current} / {total} 页", "第 {current} / {total} 頁", "Page {current} of {total}", "{current} / {total} ページ", "{current} / {total} 페이지", "Page {current} sur {total}", "Seite {current} von {total}", "Página {current} de {total}", "Página {current} de {total}", "Стр. {current} из {total}", "الصفحة {current} من {total}"],
  ["common.noDescription", "暂无描述。", "暫無描述。", "No description yet.", "説明はありません。", "아직 설명이 없습니다.", "Aucune description.", "Noch keine Beschreibung.", "Aún no hay descripción.", "Ainda sem descrição.", "Описания пока нет.", "لا يوجد وصف بعد."],
  ["common.skipContent", "跳到主要内容", "跳到主要內容", "Skip to main content", "メインコンテンツへ移動", "주요 콘텐츠로 건너뛰기", "Aller au contenu principal", "Zum Hauptinhalt springen", "Ir al contenido principal", "Ir para o conteúdo principal", "Перейти к основному содержимому", "الانتقال إلى المحتوى الرئيسي"],
  ["common.openNavigation", "打开导航", "開啟導覽", "Open navigation", "ナビゲーションを開く", "탐색 열기", "Ouvrir la navigation", "Navigation öffnen", "Abrir navegación", "Abrir navegação", "Открыть навигацию", "فتح التنقل"],
  ["common.closeNavigation", "关闭导航", "關閉導覽", "Close navigation", "ナビゲーションを閉じる", "탐색 닫기", "Fermer la navigation", "Navigation schließen", "Cerrar navegación", "Fechar navegação", "Закрыть навигацию", "إغلاق التنقل"],
  ["common.mainNavigation", "主导航", "主導覽", "Main navigation", "メインナビゲーション", "주 탐색", "Navigation principale", "Hauptnavigation", "Navegación principal", "Navegação principal", "Основная навигация", "التنقل الرئيسي"],
  ["common.searchAssets", "搜索资产", "搜尋資產", "Search assets", "アセットを検索", "자산 검색", "Rechercher des actifs", "Assets suchen", "Buscar activos", "Pesquisar ativos", "Поиск ресурсов", "البحث في الأصول"],
  ["common.clearSearch", "清除搜索", "清除搜尋", "Clear search", "検索をクリア", "검색 지우기", "Effacer la recherche", "Suche leeren", "Borrar búsqueda", "Limpar pesquisa", "Очистить поиск", "مسح البحث"],
  ["common.registry", "注册表", "登錄表", "Registry", "レジストリ", "레지스트리", "Registre", "Registry", "Registro", "Registro", "Реестр", "السجل"],
  ["common.localUser", "本地用户", "本機使用者", "Local user", "ローカルユーザー", "로컬 사용자", "Utilisateur local", "Lokaler Benutzer", "Usuario local", "Usuário local", "Локальный пользователь", "المستخدم المحلي"],
  ["common.localUserInitial", "本", "本", "L", "ロ", "로", "L", "L", "L", "L", "Л", "م"],
  ["common.assetStatistics", "资产统计", "資產統計", "Asset statistics", "アセット統計", "자산 통계", "Statistiques des actifs", "Asset-Statistik", "Estadísticas de activos", "Estatísticas de ativos", "Статистика ресурсов", "إحصاءات الأصول"],
  ["common.logicalAssets", "{count} 个逻辑资产", "{count} 個邏輯資產", "{count} logical assets", "論理アセット {count} 件", "논리 자산 {count}개", "{count} actifs logiques", "{count} logische Assets", "{count} activos lógicos", "{count} ativos lógicos", "{count} логических ресурсов", "{count} أصل منطقي"],
  ["common.selectPage", "选择本页", "選擇本頁", "Select page", "このページを選択", "이 페이지 선택", "Sélectionner la page", "Seite auswählen", "Seleccionar página", "Selecionar página", "Выбрать страницу", "تحديد الصفحة"],
  ["common.selectAllMatches", "选择全部匹配", "選擇全部符合項", "Select all matches", "一致項目をすべて選択", "일치 항목 모두 선택", "Sélectionner tous les résultats", "Alle Treffer auswählen", "Seleccionar coincidencias", "Selecionar correspondências", "Выбрать все совпадения", "تحديد كل النتائج"],
  ["common.export", "导出", "匯出", "Export", "エクスポート", "내보내기", "Exporter", "Exportieren", "Exportar", "Exportar", "Экспорт", "تصدير"],
  ["common.manageSelected", "处理所选", "處理所選", "Manage selected", "選択項目を処理", "선택 항목 처리", "Traiter la sélection", "Auswahl bearbeiten", "Gestionar selección", "Gerenciar seleção", "Обработать выбранное", "إدارة المحدد"],
  ["common.assets", "资产", "資產", "Assets", "アセット", "자산", "Actifs", "Assets", "Activos", "Ativos", "Ресурсы", "الأصول"],
  ["common.toolsProjects", "工具 / 项目", "工具 / 專案", "Tools / projects", "ツール / プロジェクト", "도구 / 프로젝트", "Outils / projets", "Tools / Projekte", "Herramientas / proyectos", "Ferramentas / projetos", "Инструменты / проекты", "الأدوات / المشاريع"],
  ["common.versions", "版本", "版本", "Versions", "バージョン", "버전", "Versions", "Versionen", "Versiones", "Versões", "Версии", "الإصدارات"],
  ["common.status", "状态", "狀態", "Status", "状態", "상태", "État", "Status", "Estado", "Status", "Статус", "الحالة"],
  ["common.typeFilter", "类型筛选", "類型篩選", "Type filter", "種類フィルター", "유형 필터", "Filtre de type", "Typfilter", "Filtro de tipo", "Filtro de tipo", "Фильтр типа", "تصفية النوع"],
  ["common.stateFilter", "状态筛选", "狀態篩選", "Status filter", "状態フィルター", "상태 필터", "Filtre d’état", "Statusfilter", "Filtro de estado", "Filtro de status", "Фильтр статуса", "تصفية الحالة"],
  ["common.sort", "排序", "排序", "Sort", "並べ替え", "정렬", "Trier", "Sortieren", "Ordenar", "Ordenar", "Сортировка", "الترتيب"],
  ["common.notLinked", "未关联", "未關聯", "Not linked", "未関連", "연결 안 됨", "Non lié", "Nicht verknüpft", "Sin vincular", "Não vinculado", "Не связано", "غير مرتبط"],
  ["common.previous", "上一页", "上一頁", "Previous", "前へ", "이전", "Précédent", "Zurück", "Anterior", "Anterior", "Назад", "السابق"],
  ["common.next", "下一页", "下一頁", "Next", "次へ", "다음", "Suivant", "Weiter", "Siguiente", "Próximo", "Далее", "التالي"],
  ["common.add", "新增", "新增", "Add", "追加", "추가", "Ajouter", "Hinzufügen", "Añadir", "Adicionar", "Добавить", "إضافة"],
  ["common.enabled", "已启用", "已啟用", "Enabled", "有効", "활성화됨", "Activé", "Aktiviert", "Activado", "Ativado", "Включено", "مفعّل"],
  ["common.disabled", "已停用", "已停用", "Disabled", "無効", "비활성화됨", "Désactivé", "Deaktiviert", "Desactivado", "Desativado", "Отключено", "معطّل"],
  ["common.confirm", "确认", "確認", "Confirm", "確認", "확인", "Confirmer", "Bestätigen", "Confirmar", "Confirmar", "Подтвердить", "تأكيد"],
  ["common.apply", "应用", "套用", "Apply", "適用", "적용", "Appliquer", "Anwenden", "Aplicar", "Aplicar", "Применить", "تطبيق"],
  ["common.restore", "恢复", "還原", "Restore", "復元", "복원", "Restaurer", "Wiederherstellen", "Restaurar", "Restaurar", "Восстановить", "استعادة"],
  ["common.details", "详情", "詳情", "Details", "詳細", "세부 정보", "Détails", "Details", "Detalles", "Detalhes", "Сведения", "التفاصيل"],
  ["search.placeholder", "搜索名称、能力、工具或项目…", "搜尋名稱、能力、工具或專案…", "Search names, capabilities, tools, or projects…", "名前、機能、ツール、プロジェクトを検索…", "이름, 기능, 도구 또는 프로젝트 검색…", "Rechercher noms, capacités, outils ou projets…", "Namen, Fähigkeiten, Tools oder Projekte suchen…", "Buscar nombres, capacidades, herramientas o proyectos…", "Pesquisar nomes, capacidades, ferramentas ou projetos…", "Поиск имён, возможностей, инструментов или проектов…", "ابحث في الأسماء أو القدرات أو الأدوات أو المشاريع…"],
  ["source.private", "本机私有资产库", "本機私有資產庫", "Private local asset library", "ローカルプライベートアセットライブラリ", "로컬 비공개 자산 라이브러리", "Bibliothèque locale privée", "Private lokale Asset-Bibliothek", "Biblioteca local privada", "Biblioteca local privada", "Локальная приватная библиотека", "مكتبة الأصول المحلية الخاصة"],
  ["source.local", "本地事实源", "本地事實源", "Local source of truth", "ローカル信頼性ソース", "로컬 신뢰 소스", "Source locale de vérité", "Lokale Wahrheitsquelle", "Fuente local de verdad", "Fonte local da verdade", "Локальный источник истины", "مصدر الحقيقة المحلي"],
  ["source.watching", "自动监听中", "自動監聽中", "Watching automatically", "自動監視中", "자동 감시 중", "Surveillance automatique", "Automatische Überwachung", "Supervisión automática", "Monitoramento automático", "Автоматическое наблюдение", "مراقبة تلقائية"],
  ["source.connecting", "正在连接", "正在連線", "Connecting", "接続中", "연결 중", "Connexion", "Verbindung wird hergestellt", "Conectando", "Conectando", "Подключение", "جارٍ الاتصال"],
  ["source.lastCheck", "最后检查", "最後檢查", "Last checked", "最終確認", "마지막 확인", "Dernière vérification", "Zuletzt geprüft", "Última comprobación", "Última verificação", "Последняя проверка", "آخر فحص"],
  ["release.bannerTitle", "发行洁净版", "發行潔淨版", "Clean public release", "クリーン公開版", "클린 공개 배포판", "Version publique propre", "Saubere öffentliche Version", "Versión pública limpia", "Versão pública limpa", "Чистая публичная версия", "إصدار عام نظيف"],
  ["release.bannerBody", "内置 Agent 0 · 内置 Skill 0 · 只有你手动刷新后，才会在本机建立当前设备的私有资产索引。", "內建 Agent 0 · 內建 Skill 0 · 只有你手動重新整理後，才會在本機建立當前裝置的私有資產索引。", "0 bundled Agents · 0 bundled Skills · A private index for this device is created only after you refresh manually.", "内蔵 Agent 0 · 内蔵 Skill 0 · 手動更新後のみ、このデバイスのプライベートインデックスが作成されます。", "내장 Agent 0 · 내장 Skill 0 · 수동으로 새로 고침한 후에만 이 기기의 비공개 인덱스가 생성됩니다.", "0 Agent intégré · 0 Skill intégré · L’index privé de cet appareil n’est créé qu’après une actualisation manuelle.", "0 gebündelte Agents · 0 gebündelte Skills · Ein privater Geräteindex wird erst nach manueller Aktualisierung erstellt.", "0 Agents incluidos · 0 Skills incluidos · El índice privado del dispositivo solo se crea tras una actualización manual.", "0 Agents incluídos · 0 Skills incluídos · O índice privado do dispositivo só é criado após atualização manual.", "0 встроенных Agents · 0 встроенных Skills · Приватный индекс создаётся только после ручного обновления.", "0 Agent مضمن · 0 Skill مضمن · لا يُنشأ فهرس خاص لهذا الجهاز إلا بعد التحديث اليدوي."],
  ["loading.title", "正在建立本机资产视图", "正在建立本機資產視圖", "Building the local asset view", "ローカルアセットビューを構築中", "로컬 자산 뷰 구성 중", "Construction de la vue locale", "Lokale Asset-Ansicht wird erstellt", "Creando la vista de activos local", "Criando a visão local de ativos", "Создаётся локальное представление", "جارٍ إنشاء عرض الأصول المحلية"],
  ["loading.body", "读取 Agent、Skill、项目关系、哈希和验证状态…", "讀取 Agent、Skill、專案關係、雜湊和驗證狀態…", "Reading Agents, Skills, project links, hashes, and verification state…", "Agent、Skill、プロジェクト関係、ハッシュ、検証状態を読み込み中…", "Agent, Skill, 프로젝트 관계, 해시 및 검증 상태 로드 중…", "Lecture des Agents, Skills, liens de projet, hachages et validations…", "Agents, Skills, Projektbezüge, Hashes und Prüfstatus werden gelesen…", "Leyendo Agents, Skills, relaciones, hashes y verificaciones…", "Lendo Agents, Skills, relações, hashes e verificações…", "Чтение Agents, Skills, связей, хешей и статусов…", "جارٍ قراءة Agents وSkills وعلاقات المشاريع والتجزئات وحالة التحقق…"],
  ["error.registryTitle", "无法读取统一注册表", "無法讀取統一登錄表", "Unable to read the unified registry", "統合レジストリを読み込めません", "통합 레지스트리를 읽을 수 없습니다", "Impossible de lire le registre unifié", "Einheitliche Registry kann nicht gelesen werden", "No se puede leer el registro unificado", "Não foi possível ler o registro unificado", "Не удаётся прочитать единый реестр", "تعذرت قراءة السجل الموحد"],
  ["error.reconnect", "重新连接", "重新連線", "Reconnect", "再接続", "다시 연결", "Reconnecter", "Erneut verbinden", "Reconectar", "Reconectar", "Переподключить", "إعادة الاتصال"],
  ["overview.eyebrow", "本地能力系统", "本地能力系統", "LOCAL CAPABILITY SYSTEM", "ローカル機能システム", "로컬 기능 시스템", "SYSTÈME DE CAPACITÉS LOCAL", "LOKALES FÄHIGKEITSSYSTEM", "SISTEMA LOCAL DE CAPACIDADES", "SISTEMA LOCAL DE CAPACIDADES", "ЛОКАЛЬНАЯ СИСТЕМА ВОЗМОЖНОСТЕЙ", "نظام القدرات المحلي"],
  ["overview.title", "你的 Agent 与 Skill，终于在同一张地图上。", "你的 Agent 與 Skill，終於在同一張地圖上。", "Your Agents and Skills, finally on one map.", "Agent と Skill を、ひとつのマップに。", "Agent와 Skill을 하나의 지도에서.", "Vos Agents et Skills, enfin sur une seule carte.", "Ihre Agents und Skills – endlich auf einer Karte.", "Tus Agents y Skills, por fin en un solo mapa.", "Seus Agents e Skills, finalmente em um só mapa.", "Ваши Agents и Skills — наконец на одной карте.", "Agents وSkills الخاصة بك، أخيرًا على خريطة واحدة."],
  ["overview.subtitle", "汇总本机定义、项目采用、归档快照和可复用版本。只报告有证据的状态，不把“文件存在”误写成“已经验证”。", "彙總本機定義、專案採用、歸檔快照和可複用版本。只報告有證據的狀態，不把「檔案存在」誤寫成「已驗證」。", "Unify local definitions, project adoption, archived snapshots, and reusable versions. Only evidence-backed states are reported; file presence is never called verification.", "ローカル定義、プロジェクト採用、アーカイブ、再利用可能バージョンを統合。証拠のある状態だけを報告し、ファイルの存在を検証済みとはみなしません。", "로컬 정의, 프로젝트 사용, 아카이브 스냅샷, 재사용 버전을 통합합니다. 증거가 있는 상태만 보고하며 파일 존재를 검증으로 간주하지 않습니다.", "Réunit les définitions locales, l’adoption par projet, les instantanés archivés et les versions réutilisables. Seuls les états prouvés sont rapportés.", "Vereint lokale Definitionen, Projektnutzung, Archiv-Snapshots und wiederverwendbare Versionen. Nur belegte Zustände werden gemeldet.", "Unifica definiciones locales, adopción por proyecto, instantáneas archivadas y versiones reutilizables. Solo se informan estados con evidencia.", "Reúne definições locais, adoção por projeto, snapshots arquivados e versões reutilizáveis. Apenas estados com evidência são reportados.", "Объединяет локальные определения, использование в проектах, архивы и повторно используемые версии. Сообщаются только подтверждённые статусы.", "يوحّد التعريفات المحلية واعتماد المشروع واللقطات المؤرشفة والإصدارات القابلة لإعادة الاستخدام. لا تُعرض إلا الحالات المدعومة بالأدلة."],
  ["overview.refreshLocal", "刷新本机资产", "重新整理本機資產", "Refresh local assets", "ローカルアセットを更新", "로컬 자산 새로 고침", "Actualiser les actifs locaux", "Lokale Assets aktualisieren", "Actualizar activos locales", "Atualizar ativos locais", "Обновить локальные ресурсы", "تحديث الأصول المحلية"],
  ["overview.refreshing", "正在刷新…", "正在重新整理…", "Refreshing…", "更新中…", "새로 고침 중…", "Actualisation…", "Wird aktualisiert…", "Actualizando…", "Atualizando…", "Обновление…", "جارٍ التحديث…"],
  ["metric.assets", "Agent / Skill 资产", "Agent / Skill 資產", "Agent / Skill assets", "Agent / Skill アセット", "Agent / Skill 자산", "Actifs Agent / Skill", "Agent-/Skill-Assets", "Activos Agent / Skill", "Ativos Agent / Skill", "Ресурсы Agent / Skill", "أصول Agent / Skill"],
  ["metric.definitions", "{definitions} 个定义 · {support} 条支持记录另计", "{definitions} 個定義 · {support} 條支援記錄另計", "{definitions} definitions · {support} support records counted separately", "{definitions} 定義 · {support} サポート記録は別計", "정의 {definitions}개 · 지원 레코드 {support}개 별도", "{definitions} définitions · {support} fiches de support séparées", "{definitions} Definitionen · {support} Supporteinträge separat", "{definitions} definiciones · {support} registros de soporte aparte", "{definitions} definições · {support} registros de suporte separados", "{definitions} определений · {support} служебных записей отдельно", "{definitions} تعريف · {support} سجل دعم منفصل"],
  ["metric.toolSurfaces", "跨 {count} 个工具面", "橫跨 {count} 個工具介面", "Across {count} tool surfaces", "{count} のツール面", "{count}개 도구 표면", "Sur {count} surfaces d’outil", "Auf {count} Tool-Oberflächen", "En {count} superficies de herramienta", "Em {count} superfícies de ferramenta", "В {count} инструментах", "عبر {count} واجهات أدوات"],
  ["metric.uniqueHashes", "{count} 个唯一内容哈希", "{count} 個唯一內容雜湊", "{count} unique content hashes", "{count} 一意コンテンツハッシュ", "고유 콘텐츠 해시 {count}개", "{count} hachages de contenu uniques", "{count} eindeutige Inhalts-Hashes", "{count} hashes de contenido únicos", "{count} hashes de conteúdo exclusivos", "{count} уникальных хешей", "{count} تجزئة محتوى فريدة"],
  ["metric.reusable", "可直接复用", "可直接複用", "Directly reusable", "すぐに再利用可能", "즉시 재사용 가능", "Directement réutilisable", "Direkt wiederverwendbar", "Reutilizable directamente", "Reutilizável diretamente", "Готово к повторному использованию", "قابل لإعادة الاستخدام مباشرة"],
  ["metric.reusableEvidence", "固定版本 + 哈希 + 验证证据", "固定版本 + 雜湊 + 驗證證據", "Pinned version + hash + verification evidence", "固定バージョン + ハッシュ + 検証証拠", "고정 버전 + 해시 + 검증 증거", "Version figée + hachage + preuve", "Fixierte Version + Hash + Nachweis", "Versión fijada + hash + evidencia", "Versão fixada + hash + evidência", "Закреплённая версия + хеш + доказательство", "إصدار مثبت + تجزئة + دليل تحقق"],
  ["status.pendingDecision", "需要判断", "需要判斷", "Decision required", "判断が必要", "판단 필요", "Décision requise", "Entscheidung erforderlich", "Requiere decisión", "Requer decisão", "Требуется решение", "يتطلب قرارًا"],
  ["status.versionTrustQueue", "版本与可信度队列", "版本與可信度佇列", "Version & trust queue", "バージョンと信頼性キュー", "버전 및 신뢰도 대기열", "File des versions et de confiance", "Versions- und Vertrauenswarteschlange", "Cola de versiones y confianza", "Fila de versões e confiança", "Очередь версий и доверия", "قائمة الإصدارات والثقة"],
  ["status.multiVersion", "多版本待选择", "多版本待選擇", "Multiple versions to choose", "複数バージョンから選択", "다중 버전 선택 대기", "Plusieurs versions à choisir", "Mehrere Versionen zur Auswahl", "Varias versiones por elegir", "Várias versões para escolher", "Выбор из нескольких версий", "إصدارات متعددة بانتظار الاختيار"],
  ["status.licensePending", "许可证待确认", "授權待確認", "License awaiting confirmation", "ライセンス確認待ち", "라이선스 확인 대기", "Licence à confirmer", "Lizenzbestätigung ausstehend", "Licencia pendiente de confirmación", "Licença aguardando confirmação", "Лицензия ожидает подтверждения", "الترخيص بانتظار التأكيد"],
  ["status.notPromoted", "尚未晋升", "尚未晉升", "Not promoted yet", "未昇格", "아직 승격되지 않음", "Pas encore promu", "Noch nicht hochgestuft", "Aún no promovido", "Ainda não promovido", "Ещё не повышено", "لم تتم الترقية بعد"],
  ["status.truthBoundary", "真值边界", "真值邊界", "Truth boundary", "真値境界", "진실 경계", "Limite de vérité", "Wahrheitsgrenze", "Límite de verdad", "Limite de verdade", "Граница истины", "حدود الحقيقة"],
  ["status.maturity", "资产成熟度", "資產成熟度", "Asset maturity", "アセット成熟度", "자산 성숙도", "Maturité des actifs", "Asset-Reife", "Madurez de activos", "Maturidade dos ativos", "Зрелость ресурсов", "نضج الأصول"],
  ["status.readyAssets", "已就绪资产", "已就緒資產", "Ready assets", "準備完了アセット", "준비된 자산", "Actifs prêts", "Bereite Assets", "Activos listos", "Ativos prontos", "Готовые ресурсы", "الأصول الجاهزة"],
  ["status.totalCoverage", "总资产覆盖", "總資產覆蓋", "Total asset coverage", "総アセットカバレッジ", "전체 자산 커버리지", "Couverture totale", "Gesamtabdeckung", "Cobertura total", "Cobertura total", "Общий охват", "تغطية الأصول الكلية"],
  ["status.visible", "本机 / 项目可见", "本機 / 專案可見", "Visible locally / in projects", "ローカル / プロジェクトで表示", "로컬 / 프로젝트에서 보임", "Visible localement / dans les projets", "Lokal / in Projekten sichtbar", "Visible localmente / en proyectos", "Visível localmente / em projetos", "Видимо локально / в проектах", "مرئي محليًا / في المشاريع"],
  ["status.versionConflict", "多版本冲突", "多版本衝突", "Version conflicts", "バージョン競合", "버전 충돌", "Conflits de versions", "Versionskonflikte", "Conflictos de versión", "Conflitos de versão", "Конфликты версий", "تعارضات الإصدارات"],
  ["status.latestPolicy", "最新不等于覆盖。新项目选择最新已验证版本；已有项目继续锁定回执版本，升级必须单独验证。", "最新不等於覆蓋。新專案選擇最新已驗證版本；已有專案繼續鎖定回執版本，升級必須單獨驗證。", "Latest does not mean overwrite. New projects use the latest verified version; existing projects keep their receipt-pinned version until an upgrade is verified separately.", "最新は上書きを意味しません。新規プロジェクトは最新の検証済み版を使い、既存プロジェクトはアップグレードを別途検証するまで固定版を維持します。", "최신이 덮어쓰기를 의미하지는 않습니다. 새 프로젝트는 최신 검증 버전을 사용하고 기존 프로젝트는 별도 검증 전까지 고정 버전을 유지합니다.", "La version la plus récente n’écrase rien. Les nouveaux projets utilisent la dernière version vérifiée; les projets existants restent figés jusqu’à validation d’une mise à niveau.", "Neu bedeutet nicht überschreiben. Neue Projekte nutzen die neueste geprüfte Version; bestehende bleiben bis zur separat geprüften Aktualisierung fixiert.", "Lo más reciente no sobrescribe. Los proyectos nuevos usan la última versión verificada; los existentes mantienen su versión fijada hasta validar la actualización.", "Mais recente não significa sobrescrever. Novos projetos usam a última versão verificada; os existentes mantêm a versão fixada até validar a atualização.", "Новая версия не означает перезапись. Новые проекты берут последнюю проверенную версию; существующие остаются закреплёнными до отдельной проверки обновления.", "الأحدث لا يعني الكتابة فوق القديم. تستخدم المشاريع الجديدة آخر إصدار متحقق منه، وتبقى المشاريع الحالية مثبتة حتى التحقق من الترقية بشكل منفصل."],
  ["projects.coverage", "项目覆盖", "專案覆蓋", "Project coverage", "プロジェクトカバレッジ", "프로젝트 커버리지", "Couverture des projets", "Projektabdeckung", "Cobertura de proyectos", "Cobertura de projetos", "Охват проектов", "تغطية المشاريع"],
  ["projects.densest", "资产密度最高的项目", "資產密度最高的專案", "Projects with the highest asset density", "アセット密度の高いプロジェクト", "자산 밀도가 가장 높은 프로젝트", "Projets les plus denses en actifs", "Projekte mit höchster Asset-Dichte", "Proyectos con mayor densidad de activos", "Projetos com maior densidade de ativos", "Проекты с наибольшей плотностью ресурсов", "المشاريع الأعلى كثافة في الأصول"],
  ["strategy.kicker", "持续更新", "持續更新", "Continuous updates", "継続更新", "지속적 업데이트", "Mises à jour continues", "Kontinuierliche Updates", "Actualizaciones continuas", "Atualizações contínuas", "Непрерывные обновления", "تحديثات مستمرة"],
  ["strategy.title", "刷新策略", "重新整理策略", "Refresh strategy", "更新戦略", "새로 고침 전략", "Stratégie d’actualisation", "Aktualisierungsstrategie", "Estrategia de actualización", "Estratégia de atualização", "Стратегия обновления", "استراتيجية التحديث"],
  ["strategy.watchTitle", "轻量监听统一注册表", "輕量監聽統一登錄表", "Lightweight registry watch", "レジストリの軽量監視", "가벼운 레지스트리 감시", "Surveillance légère du registre", "Leichtgewichtige Registry-Überwachung", "Supervisión ligera del registro", "Monitoramento leve do registro", "Лёгкое наблюдение за реестром", "مراقبة خفيفة للسجل"],
  ["strategy.watchBody", "每 60 秒仅检查元数据；后台暂停，变化后才读取正文", "每 60 秒只檢查後設資料；後台暫停，變化後才讀取正文", "Metadata only every 60 seconds; pauses in background and reads content only after changes", "60 秒ごとにメタデータのみ確認。バックグラウンドで停止し、変更時のみ本文を読みます", "60초마다 메타데이터만 확인하고 백그라운드에서는 중지하며 변경 시에만 본문을 읽습니다", "Métadonnées seulement toutes les 60 s; pause en arrière-plan et lecture du contenu uniquement après changement", "Nur Metadaten alle 60 Sekunden; im Hintergrund pausiert, Inhalt erst bei Änderung", "Solo metadatos cada 60 segundos; pausa en segundo plano y lee contenido solo tras cambios", "Apenas metadados a cada 60 segundos; pausa em segundo plano e lê conteúdo só após mudanças", "Только метаданные раз в 60 секунд; в фоне пауза, текст читается только при изменениях", "فحص البيانات الوصفية فقط كل 60 ثانية؛ يتوقف في الخلفية ويقرأ المحتوى فقط بعد التغيير"],
  ["strategy.localTitle", "本机快速刷新", "本機快速重新整理", "Fast local refresh", "ローカル高速更新", "빠른 로컬 새로 고침", "Actualisation locale rapide", "Schnelle lokale Aktualisierung", "Actualización local rápida", "Atualização local rápida", "Быстрое локальное обновление", "تحديث محلي سريع"],
  ["strategy.localBody", "重新盘点工具安装目录，再重建逻辑资产视图", "重新盤點工具安裝目錄，再重建邏輯資產視圖", "Re-inventory tool install directories, then rebuild the logical asset view", "ツールのインストール先を再棚卸し、論理アセットビューを再構築", "도구 설치 디렉터리를 다시 조사한 후 논리 자산 뷰를 재구성", "Réinventorie les dossiers d’installation puis reconstruit la vue logique", "Tool-Installationsordner neu inventarisieren und logische Asset-Ansicht aufbauen", "Reinventaría los directorios y reconstruye la vista lógica", "Reinventaria os diretórios e reconstrói a visão lógica", "Повторная инвентаризация каталогов и пересборка логического вида", "إعادة جرد مجلدات تثبيت الأدوات ثم إعادة بناء العرض المنطقي"],
  ["strategy.fullTitle", "全项目深度刷新", "全專案深度重新整理", "Deep refresh across projects", "全プロジェクト深度更新", "전체 프로젝트 심층 새로 고침", "Actualisation approfondie des projets", "Tiefe Aktualisierung aller Projekte", "Actualización profunda de proyectos", "Atualização profunda dos projetos", "Глубокое обновление проектов", "تحديث عميق عبر المشاريع"],
  ["strategy.fullPublic", "显式触发，只扫描你在统一控制中手动登记的自定义入口", "明確觸發，只掃描你在統一控制中手動登錄的自訂入口", "Explicit only; scans custom roots you manually registered in Unified Control", "明示的に実行し、統合コントロールで手動登録したカスタムルートのみをスキャン", "명시적으로 실행하며 통합 제어에서 수동 등록한 사용자 지정 루트만 스캔", "Déclenchement explicite; analyse seulement les racines ajoutées manuellement", "Nur explizit; scannt manuell registrierte benutzerdefinierte Wurzeln", "Solo explícito; escanea las raíces registradas manualmente", "Somente explícito; verifica raízes registradas manualmente", "Только явный запуск; сканируются ручные корни", "تشغيل صريح فقط؛ يفحص المسارات المخصصة المسجلة يدويًا"],
  ["strategy.fullPrivate", "显式触发，逐项目扫描；卡顿路径会超时并保留为未解析", "明確觸發，逐專案掃描；卡住路徑會逾時並保留為未解析", "Explicit only; scans project by project, timing out stalled paths without hiding them", "明示的に実行し、プロジェクトごとにスキャン。停滞したパスはタイムアウトし未解決のまま保持", "명시적으로 실행하고 프로젝트별로 스캔하며 멈춘 경로는 시간 초과 후 미해결로 보존", "Déclenchement explicite, projet par projet; les chemins bloqués expirent et restent non résolus", "Nur explizit, Projekt für Projekt; blockierte Pfade laufen ab und bleiben ungelöst", "Solo explícito, proyecto por proyecto; las rutas bloqueadas expiran y quedan sin resolver", "Somente explícito, projeto a projeto; caminhos bloqueados expiram e ficam não resolvidos", "Только явный запуск, по проектам; зависшие пути остаются неразрешёнными", "تشغيل صريح فقط مشروعًا بمشروع؛ تنتهي مهلة المسارات المتوقفة وتبقى غير محلولة"],
  ["strategy.candidateTitle", "优化进入候选队列", "優化進入候選佇列", "Optimization enters a candidate queue", "最適化を候補キューへ", "최적화를 후보 대기열로", "L’optimisation entre en file candidate", "Optimierung kommt in die Kandidatenwarteschlange", "La optimización entra en cola de candidatos", "A otimização entra na fila de candidatos", "Оптимизация попадает в очередь кандидатов", "يدخل التحسين قائمة المرشحين"],
  ["strategy.candidateBody", "验证通过后才晋升新版本，绝不静默覆盖", "驗證通過後才晉升新版本，絕不靜默覆蓋", "Promote a new version only after verification; never overwrite silently", "検証後のみ新バージョンを昇格し、無断上書きはしません", "검증 후에만 새 버전을 승격하고 조용히 덮어쓰지 않습니다", "Promouvoir seulement après validation; jamais d’écrasement silencieux", "Neue Version erst nach Prüfung hochstufen; nie still überschreiben", "Promover solo tras verificar; nunca sobrescribir en silencio", "Promover somente após verificar; nunca sobrescrever silenciosamente", "Повышать версию только после проверки; никогда не перезаписывать молча", "لا تتم ترقية إصدار جديد إلا بعد التحقق؛ ولا كتابة فوقه بصمت"],
  ["drawer.details", "资产详情", "資產詳情", "Asset details", "アセット詳細", "자산 상세", "Détails de l’actif", "Asset-Details", "Detalles del activo", "Detalhes do ativo", "Сведения о ресурсе", "تفاصيل الأصل"],
  ["drawer.usage", "使用边界", "使用邊界", "Usage boundary", "使用境界", "사용 경계", "Limite d’usage", "Nutzungsgrenze", "Límite de uso", "Limite de uso", "Граница использования", "حدود الاستخدام"],
  ["drawer.usageFallback", "作为本机或项目资产记录；当前没有足够证据证明可直接复用。", "作為本機或專案資產記錄；當前沒有足夠證據證明可直接複用。", "Recorded as a local or project asset; there is not yet enough evidence for direct reuse.", "ローカルまたはプロジェクトアセットとして記録済みですが、直接再利用できる証拠はまだ不足しています。", "로컬 또는 프로젝트 자산으로 기록되었으나 직접 재사용할 충분한 증거는 아직 없습니다.", "Enregistré comme actif local ou de projet; les preuves sont encore insuffisantes pour une réutilisation directe.", "Als lokales oder Projekt-Asset erfasst; für direkte Wiederverwendung fehlen noch Nachweise.", "Registrado como activo local o de proyecto; aún no hay evidencia suficiente para reutilizarlo directamente.", "Registrado como ativo local ou de projeto; ainda não há evidência suficiente para reutilização direta.", "Записано как локальный или проектный ресурс; для прямого повторного использования пока нет достаточных доказательств.", "مسجل كأصل محلي أو للمشروع؛ لا توجد أدلة كافية بعد لإعادة الاستخدام مباشرة."],
  ["drawer.toolsProjects", "工具与项目", "工具與專案", "Tools & projects", "ツールとプロジェクト", "도구 및 프로젝트", "Outils et projets", "Tools & Projekte", "Herramientas y proyectos", "Ferramentas e projetos", "Инструменты и проекты", "الأدوات والمشاريع"],
  ["drawer.unlinked", "尚未关联", "尚未關聯", "Not linked yet", "未関連", "아직 연결되지 않음", "Pas encore lié", "Noch nicht verknüpft", "Aún sin vincular", "Ainda não vinculado", "Ещё не связано", "غير مرتبط بعد"],
  ["drawer.versions", "内容版本", "內容版本", "Content versions", "コンテンツバージョン", "콘텐츠 버전", "Versions du contenu", "Inhaltsversionen", "Versiones de contenido", "Versões de conteúdo", "Версии содержимого", "إصدارات المحتوى"],
  ["drawer.version", "版本 {index}", "版本 {index}", "Version {index}", "バージョン {index}", "버전 {index}", "Version {index}", "Version {index}", "Versión {index}", "Versão {index}", "Версия {index}", "الإصدار {index}"],
  ["drawer.moreLocations", "另有 {count} 个位置", "另有 {count} 個位置", "{count} more locations", "他 {count} ヶ所", "위치 {count}개 더 있음", "{count} emplacements supplémentaires", "{count} weitere Orte", "{count} ubicaciones más", "Mais {count} locais", "Ещё {count} расположений", "{count} مواقع إضافية"],
  ["drawer.verification", "验证与复用", "驗證與複用", "Verification & reuse", "検証と再利用", "검증 및 재사용", "Vérification et réutilisation", "Prüfung & Wiederverwendung", "Verificación y reutilización", "Verificação e reutilização", "Проверка и повторное использование", "التحقق وإعادة الاستخدام"],
  ["drawer.fixedVersion", "固定版本", "固定版本", "Pinned version", "固定バージョン", "고정 버전", "Version figée", "Fixierte Version", "Versión fijada", "Versão fixada", "Закреплённая версия", "إصدار مثبت"],
  ["drawer.registered", "已登记", "已登錄", "Registered", "登録済み", "등록됨", "Enregistré", "Registriert", "Registrado", "Registrado", "Зарегистрировано", "مسجل"],
  ["drawer.notReady", "当前没有“已验证可直接复用”的固定版本。文件存在不等于运行时已加载或效果已验证。", "當前沒有「已驗證可直接複用」的固定版本。檔案存在不等於執行時已載入或效果已驗證。", "There is no pinned version verified for direct reuse. File presence does not prove runtime loading or outcome quality.", "直接再利用可能と検証された固定版はありません。ファイルの存在は実行時ロードや結果品質の証明ではありません。", "직접 재사용을 검증한 고정 버전이 없습니다. 파일 존재는 런타임 로드나 결과 품질을 증명하지 않습니다.", "Aucune version figée n’est validée pour réutilisation directe. La présence d’un fichier ne prouve ni le chargement ni la qualité.", "Keine fixierte Version ist für direkte Wiederverwendung geprüft. Eine Datei beweist weder Laufzeitladung noch Ergebnisqualität.", "No hay una versión fijada verificada para reutilización directa. La presencia del archivo no prueba carga ni calidad.", "Não há versão fixada verificada para reutilização direta. A presença do arquivo não prova carregamento nem qualidade.", "Нет закреплённой версии, проверенной для прямого использования. Наличие файла не доказывает загрузку или качество.", "لا يوجد إصدار مثبت متحقق منه لإعادة الاستخدام مباشرة. وجود الملف لا يثبت التحميل أو جودة النتيجة."],
  ["drawer.addExport", "加入导出", "加入匯出", "Add to export", "エクスポートに追加", "내보내기에 추가", "Ajouter à l’export", "Zum Export hinzufügen", "Añadir a exportación", "Adicionar à exportação", "Добавить в экспорт", "إضافة إلى التصدير"],
  ["drawer.agentOnly", "仅 Agent", "僅 Agent", "Agent only", "Agent のみ", "Agent만", "Agent uniquement", "Nur Agent", "Solo Agent", "Somente Agent", "Только Agent", "Agent فقط"],
  ["drawer.skillOnly", "仅 Skill", "僅 Skill", "Skill only", "Skill のみ", "Skill만", "Skill uniquement", "Nur Skill", "Solo Skill", "Somente Skill", "Только Skill", "Skill فقط"],
  ["assets.title", "全部 Agent 与 Skill", "全部 Agent 與 Skill", "All Agents & Skills", "すべての Agent と Skill", "모든 Agent와 Skill", "Tous les Agents et Skills", "Alle Agents & Skills", "Todos los Agents y Skills", "Todos os Agents e Skills", "Все Agents и Skills", "كل Agents وSkills"],
  ["assets.subtitle", "共 {count} 个匹配项；点击条目查看来源、项目关系和哈希变体。", "共 {count} 個符合項；點擊項目查看來源、專案關係和雜湊變體。", "{count} matches. Open an item to inspect sources, project links, and hash variants.", "{count} 件一致。項目を開いてソース、プロジェクト関係、ハッシュ変種を確認できます。", "{count}개 일치. 항목을 열어 출처, 프로젝트 연결, 해시 변형을 확인하세요.", "{count} résultats. Ouvrez un élément pour voir les sources, projets et variantes de hachage.", "{count} Treffer. Öffnen Sie einen Eintrag für Quellen, Projekte und Hash-Varianten.", "{count} coincidencias. Abre un elemento para ver fuentes, proyectos y variantes hash.", "{count} correspondências. Abra um item para ver fontes, projetos e variantes de hash.", "Совпадений: {count}. Откройте элемент для просмотра источников, проектов и хешей.", "{count} نتيجة. افتح عنصرًا لفحص المصادر وروابط المشاريع ومتغيرات التجزئة."],
  ["assets.ready", "可直接复用", "可直接複用", "Ready to reuse", "再利用可能", "재사용 가능", "Prêt à réutiliser", "Wiederverwendbar", "Listo para reutilizar", "Pronto para reutilizar", "Готово к использованию", "جاهز لإعادة الاستخدام"],
  ["assets.verified", "本机已验证", "本機已驗證", "Verified locally", "ローカル検証済み", "로컬 검증됨", "Vérifié localement", "Lokal geprüft", "Verificado localmente", "Verificado localmente", "Проверено локально", "تم التحقق محليًا"],
  ["assets.versionSelected", "版本已选择", "版本已選擇", "Version selected", "バージョン選択済み", "버전 선택됨", "Version sélectionnée", "Version ausgewählt", "Versión seleccionada", "Versão selecionada", "Версия выбрана", "تم تحديد الإصدار"],
  ["assets.multiVersion", "多版本", "多版本", "Multiple versions", "複数バージョン", "여러 버전", "Plusieurs versions", "Mehrere Versionen", "Varias versiones", "Várias versões", "Несколько версий", "إصدارات متعددة"],
  ["assets.pendingVerification", "待验证", "待驗證", "Pending verification", "検証待ち", "검증 대기", "En attente de vérification", "Prüfung ausstehend", "Pendiente de verificación", "Verificação pendente", "Ожидает проверки", "بانتظار التحقق"],
  ["assets.optimizedPending", "优化已应用·待刷新", "優化已套用·待重新整理", "Optimization applied · refresh pending", "最適化適用済み・更新待ち", "최적화 적용됨 · 새로 고침 대기", "Optimisation appliquée · actualisation requise", "Optimierung angewandt · Aktualisierung ausstehend", "Optimización aplicada · actualización pendiente", "Otimização aplicada · atualização pendente", "Оптимизация применена · требуется обновление", "تم تطبيق التحسين · بانتظار التحديث"],
  ["assets.selectedPending", "版本已选·待验证", "版本已選·待驗證", "Version selected · verification pending", "バージョン選択済み・検証待ち", "버전 선택됨 · 검증 대기", "Version sélectionnée · vérification requise", "Version gewählt · Prüfung ausstehend", "Versión seleccionada · verificación pendiente", "Versão selecionada · verificação pendente", "Версия выбрана · ожидает проверки", "تم تحديد الإصدار · بانتظار التحقق"],
  ["assets.licensePending", "许可已确认·待验证", "許可已確認·待驗證", "License confirmed · verification pending", "ライセンス確認済み・検証待ち", "라이선스 확인됨 · 검증 대기", "Licence confirmée · vérification requise", "Lizenz bestätigt · Prüfung ausstehend", "Licencia confirmada · verificación pendiente", "Licença confirmada · verificação pendente", "Лицензия подтверждена · ожидает проверки", "تم تأكيد الترخيص · بانتظار التحقق"],
  ["assets.visiblePending", "本机可见待验证", "本機可見待驗證", "Visible locally · verification pending", "ローカル表示・検証待ち", "로컬 표시 · 검증 대기", "Visible localement · vérification requise", "Lokal sichtbar · Prüfung ausstehend", "Visible localmente · verificación pendiente", "Visível localmente · verificação pendente", "Видимо локально · ожидает проверки", "ظاهر محليًا · بانتظار التحقق"],
  ["assets.noMatches", "没有找到匹配的资产。请缩短关键词或重置筛选。", "找不到符合的資產。請縮短關鍵字或重設篩選。", "No matching assets. Shorten the query or reset filters.", "一致するアセットがありません。検索語を短くするかフィルターをリセットしてください。", "일치하는 자산이 없습니다. 검색어를 줄이거나 필터를 초기화하세요.", "Aucun actif correspondant. Raccourcissez la recherche ou réinitialisez les filtres.", "Keine passenden Assets. Kürzen Sie die Suche oder setzen Sie die Filter zurück.", "No hay activos coincidentes. Acorta la búsqueda o restablece los filtros.", "Nenhum ativo correspondente. Reduza a busca ou redefina os filtros.", "Совпадений нет. Сократите запрос или сбросьте фильтры.", "لا توجد أصول مطابقة. اختصر البحث أو أعد ضبط عوامل التصفية."],
  ["projects.title", "项目能力图谱", "專案能力圖譜", "Project capability map", "プロジェクト機能マップ", "프로젝트 기능 지도", "Carte des capacités projet", "Projektfähigkeitskarte", "Mapa de capacidades del proyecto", "Mapa de capacidades do projeto", "Карта возможностей проектов", "خريطة قدرات المشاريع"],
  ["projects.subtitle", "从项目密度查看能力构成、复用覆盖和待处理资产；历史路径不会被当成当前采用。", "從專案密度查看能力構成、複用覆蓋和待處理資產；歷史路徑不會被視為目前採用。", "Explore capability mix, reuse coverage, and pending assets by project density; historical paths are not treated as current adoption.", "プロジェクト密度から機能構成、再利用範囲、保留アセットを確認します。履歴パスは現在の採用とはみなしません。", "프로젝트 밀도로 기능 구성, 재사용 범위, 대기 자산을 확인합니다. 과거 경로는 현재 사용으로 간주하지 않습니다.", "Explorez la composition, la couverture et les actifs en attente par densité de projet ; les anciens chemins ne valent pas adoption actuelle.", "Fähigkeitsmix, Wiederverwendung und offene Assets nach Projektdichte; alte Pfade gelten nicht als aktuelle Nutzung.", "Explora capacidades, cobertura y activos pendientes por densidad; las rutas históricas no cuentan como adopción actual.", "Explore capacidades, cobertura e ativos pendentes por densidade; caminhos históricos não contam como adoção atual.", "Состав возможностей, покрытие и ожидающие ресурсы по плотности проекта; старые пути не считаются текущим использованием.", "استكشف مزيج القدرات وتغطية إعادة الاستخدام والأصول المعلقة حسب كثافة المشروع؛ ولا تُعد المسارات القديمة اعتمادًا حاليًا."],
  ["projects.registered", "{count} 个已登记项目", "{count} 個已登錄專案", "{count} registered projects", "登録済みプロジェクト {count} 件", "등록 프로젝트 {count}개", "{count} projets enregistrés", "{count} registrierte Projekte", "{count} proyectos registrados", "{count} projetos registrados", "Зарегистрировано проектов: {count}", "{count} مشروع مسجل"],
  ["projects.search", "搜索项目名称…", "搜尋專案名稱…", "Search project names…", "プロジェクト名を検索…", "프로젝트 이름 검색…", "Rechercher un projet…", "Projektnamen suchen…", "Buscar proyectos…", "Pesquisar projetos…", "Поиск проектов…", "البحث في المشاريع…"],
  ["projects.capabilityMix", "能力构成", "能力構成", "Capability mix", "機能構成", "기능 구성", "Composition", "Fähigkeitsmix", "Composición", "Composição", "Состав", "مزيج القدرات"],
  ["projects.coverageLabel", "覆盖", "覆蓋", "Coverage", "カバレッジ", "적용 범위", "Couverture", "Abdeckung", "Cobertura", "Cobertura", "Покрытие", "التغطية"],
  ["projects.viewAssets", "查看全部资产", "查看全部資產", "View all assets", "すべてのアセットを表示", "모든 자산 보기", "Voir tous les actifs", "Alle Assets anzeigen", "Ver todos los activos", "Ver todos os ativos", "Показать все ресурсы", "عرض كل الأصول"],
  ["projects.attention", "待处理", "待處理", "Needs attention", "要対応", "처리 필요", "À traiter", "Zu bearbeiten", "Pendiente", "Pendente", "Требует внимания", "بحاجة إلى معالجة"],
  ["projects.primaryTools", "主要工具面", "主要工具介面", "Primary tool surfaces", "主要ツール面", "주요 도구 표면", "Principales surfaces d’outil", "Wichtigste Tool-Oberflächen", "Principales herramientas", "Principais ferramentas", "Основные инструменты", "واجهات الأدوات الرئيسية"],
  ["projects.representative", "代表资产", "代表資產", "Representative assets", "代表アセット", "대표 자산", "Actifs représentatifs", "Repräsentative Assets", "Activos representativos", "Ativos representativos", "Представительные ресурсы", "الأصول الممثلة"],
  ["evolution.title", "版本处置工作台", "版本處置工作台", "Version triage workbench", "バージョン対応ワークベンチ", "버전 분류 작업 공간", "Poste de tri des versions", "Arbeitsbereich zur Versionsprüfung", "Mesa de gestión de versiones", "Área de triagem de versões", "Рабочая область версий", "مساحة فرز الإصدارات"],
  ["evolution.subtitle", "先聚焦风险，再核对证据；刷新只发现变化，不自动覆盖项目锁定版本。", "先聚焦風險，再核對證據；重新整理只發現變更，不會自動覆蓋專案鎖定版本。", "Focus on risk, then verify evidence. Refresh discovers changes without overwriting pinned project versions.", "リスクを優先し、証拠を確認します。更新は変更を検出するだけで、固定版を上書きしません。", "위험을 먼저 확인한 뒤 증거를 검토합니다. 새로 고침은 변경만 찾으며 고정 버전을 덮어쓰지 않습니다.", "Priorisez le risque puis vérifiez les preuves. L’actualisation détecte les changements sans écraser les versions figées.", "Erst Risiken, dann Nachweise. Aktualisieren erkennt Änderungen, überschreibt aber keine fixierten Versionen.", "Prioriza el riesgo y verifica evidencias. Actualizar detecta cambios sin sobrescribir versiones fijadas.", "Priorize o risco e verifique evidências. Atualizar detecta mudanças sem sobrescrever versões fixadas.", "Сначала риски, затем доказательства. Обновление находит изменения, не перезаписывая закреплённые версии.", "ركّز على المخاطر ثم تحقق من الأدلة. يكتشف التحديث التغييرات دون استبدال الإصدارات المثبتة."],
  ["evolution.deepRefresh", "全项目深度刷新", "全專案深度重新整理", "Deep refresh all projects", "全プロジェクトを詳細更新", "모든 프로젝트 심층 새로 고침", "Actualisation approfondie de tous les projets", "Alle Projekte tief aktualisieren", "Actualización profunda de proyectos", "Atualização profunda dos projetos", "Глубокое обновление всех проектов", "تحديث عميق لكل المشاريع"],
  ["evolution.scanning", "深度扫描中…", "深度掃描中…", "Deep scan running…", "詳細スキャン中…", "심층 검사 중…", "Analyse approfondie…", "Tiefenscan läuft…", "Análisis profundo…", "Verificação profunda…", "Глубокое сканирование…", "جارٍ الفحص العميق…"],
  ["evolution.policy", "发现 → 比较 → 验证 / 晋升", "發現 → 比較 → 驗證 / 晉升", "Discover → compare → verify / promote", "検出 → 比較 → 検証 / 昇格", "발견 → 비교 → 검증 / 승격", "Découvrir → comparer → vérifier / promouvoir", "Erkennen → vergleichen → prüfen / freigeben", "Descubrir → comparar → verificar / promover", "Descobrir → comparar → verificar / promover", "Обнаружить → сравнить → проверить / повысить", "اكتشاف ← مقارنة ← تحقق / ترقية"],
  ["evolution.policyBody", "灵栈负责发现、聚合和证据展示；版本选择与晋升仍通过受控流程完成。", "靈棧負責發現、彙整和證據展示；版本選擇與晉升仍透過受控流程完成。", "Lingzhan discovers, aggregates, and shows evidence; version selection and promotion remain controlled workflows.", "Lingzhan は検出、集約、証拠表示を行い、バージョン選択と昇格は管理された手順で行います。", "Lingzhan은 발견, 집계, 증거 표시를 담당하며 버전 선택과 승격은 통제된 절차로 진행됩니다.", "Lingzhan détecte, agrège et présente les preuves ; sélection et promotion restent contrôlées.", "Lingzhan erkennt, bündelt und zeigt Nachweise; Auswahl und Freigabe bleiben kontrolliert.", "Lingzhan detecta, agrega y muestra evidencias; la selección y promoción siguen controladas.", "Lingzhan detecta, agrega e mostra evidências; seleção e promoção seguem controladas.", "Lingzhan обнаруживает, объединяет и показывает доказательства; выбор и повышение остаются контролируемыми.", "تكتشف Lingzhan الأدلة وتجمعها وتعرضها؛ ويظل تحديد الإصدار وترقيته ضمن إجراءات مضبوطة."],
  ["controls.title", "模型、工具路径与资产验真", "模型、工具路徑與資產驗真", "Models, tool paths & asset verification", "モデル、ツールパス、アセット検証", "모델, 도구 경로 및 자산 검증", "Modèles, chemins d’outil et vérification", "Modelle, Tool-Pfade & Asset-Prüfung", "Modelos, rutas y verificación de activos", "Modelos, caminhos e verificação de ativos", "Модели, пути инструментов и проверка", "النماذج ومسارات الأدوات والتحقق من الأصول"],
  ["controls.subtitle", "统一配置入口，分别证明连接、文件结构与真实运行；路径改动必须由用户手动触发。", "統一設定入口，分別證明連線、檔案結構與真實執行；路徑變更必須由使用者手動觸發。", "One control surface for connection, file structure, and runtime evidence. Path changes always require a manual user action.", "接続、ファイル構造、実行証拠を一元管理。パス変更は必ずユーザーが手動で実行します。", "연결, 파일 구조, 런타임 증거를 한곳에서 관리합니다. 경로 변경은 항상 사용자가 직접 실행해야 합니다.", "Une entrée unique pour les preuves de connexion, structure et exécution. Les chemins ne changent que sur action manuelle.", "Eine Oberfläche für Verbindungs-, Struktur- und Laufzeitnachweise. Pfade ändern sich nur durch Benutzeraktion.", "Un panel para conexión, estructura y ejecución. Los cambios de ruta siempre requieren acción manual.", "Um painel para conexão, estrutura e execução. Mudanças de caminho sempre exigem ação manual.", "Единая точка для проверки соединения, структуры и запуска. Пути меняются только вручную.", "واجهة موحدة لإثبات الاتصال والبنية والتشغيل. لا تتغير المسارات إلا بإجراء يدوي من المستخدم."],
  ["controls.safety", "自动检查只读 · 密钥不落盘 · 路径变更有回执", "自動檢查唯讀 · 密鑰不落盤 · 路徑變更有回執", "Read-only auto-checks · no keys on disk · path changes are receipted", "自動チェックは読み取り専用・キーは保存しない・パス変更は記録", "자동 검사는 읽기 전용 · 키 미저장 · 경로 변경 기록", "Contrôles automatiques en lecture seule · clés hors disque · changements tracés", "Automatische Checks nur lesend · keine Schlüssel auf Platte · Pfadänderungen protokolliert", "Comprobaciones de solo lectura · claves fuera del disco · cambios registrados", "Verificações somente leitura · chaves fora do disco · alterações registradas", "Автопроверки только для чтения · ключи не на диске · изменения записываются", "فحوص آلية للقراءة فقط · لا مفاتيح على القرص · تغييرات المسار موثقة"],
  ["controls.models", "模型接入", "模型接入", "Model access", "モデル接続", "모델 연결", "Accès aux modèles", "Modellzugang", "Acceso a modelos", "Acesso a modelos", "Доступ к моделям", "الوصول إلى النماذج"],
  ["controls.paths", "工具路径", "工具路徑", "Tool paths", "ツールパス", "도구 경로", "Chemins d’outil", "Tool-Pfade", "Rutas de herramientas", "Caminhos de ferramentas", "Пути инструментов", "مسارات الأدوات"],
  ["controls.audit", "Agent / Skill 验真", "Agent / Skill 驗真", "Agent / Skill verification", "Agent / Skill 検証", "Agent / Skill 검증", "Vérification Agent / Skill", "Agent-/Skill-Prüfung", "Verificación de Agent / Skill", "Verificação de Agent / Skill", "Проверка Agent / Skill", "التحقق من Agent / Skill"],
  ["model.profiles", "模型接入配置", "模型接入設定", "Model access profiles", "モデル接続設定", "모델 연결 프로필", "Profils d’accès aux modèles", "Modellzugangsprofile", "Perfiles de acceso a modelos", "Perfis de acesso a modelos", "Профили доступа к моделям", "ملفات الوصول إلى النماذج"],
  ["model.add", "新增接入", "新增接入", "Add connection", "接続を追加", "연결 추가", "Ajouter une connexion", "Verbindung hinzufügen", "Añadir conexión", "Adicionar conexão", "Добавить подключение", "إضافة اتصال"],
  ["model.count", "{count} 个模型", "{count} 個模型", "{count} models", "{count} モデル", "모델 {count}개", "{count} modèles", "{count} Modelle", "{count} modelos", "{count} modelos", "{count} моделей", "{count} نموذج"],
  ["model.default", "默认", "預設", "Default", "既定", "기본", "Par défaut", "Standard", "Predeterminado", "Padrão", "По умолчанию", "افتراضي"],
  ["model.notSelected", "未选择", "未選擇", "Not selected", "未選択", "선택 안 됨", "Non sélectionné", "Nicht ausgewählt", "Sin seleccionar", "Não selecionado", "Не выбрано", "غير محدد"],
  ["model.connect", "连接检查", "連線檢查", "Connection check", "接続確認", "연결 확인", "Vérifier la connexion", "Verbindung prüfen", "Comprobar conexión", "Verificar conexão", "Проверить соединение", "فحص الاتصال"],
  ["model.inference", "推理验真", "推理驗真", "Inference verification", "推論検証", "추론 검증", "Vérifier l’inférence", "Inferenz prüfen", "Verificar inferencia", "Verificar inferência", "Проверить вывод", "التحقق من الاستدلال"],
  ["model.profile", "编辑模型接入", "編輯模型接入", "Edit model access", "モデル接続を編集", "모델 연결 편집", "Modifier l’accès au modèle", "Modellzugang bearbeiten", "Editar acceso al modelo", "Editar acesso ao modelo", "Изменить доступ к модели", "تحرير الوصول إلى النموذج"],
  ["model.displayName", "显示名称", "顯示名稱", "Display name", "表示名", "표시 이름", "Nom affiché", "Anzeigename", "Nombre visible", "Nome de exibição", "Отображаемое имя", "اسم العرض"],
  ["model.interfaceType", "接口类型", "介面類型", "Interface type", "インターフェース種類", "인터페이스 유형", "Type d’interface", "Schnittstellentyp", "Tipo de interfaz", "Tipo de interface", "Тип интерфейса", "نوع الواجهة"],
  ["model.endpoint", "接口基础地址", "介面基礎位址", "Base endpoint", "ベースエンドポイント", "기본 엔드포인트", "Point d’accès de base", "Basis-Endpunkt", "Endpoint base", "Endpoint base", "Базовый адрес", "عنوان نقطة النهاية"],
  ["model.catalog", "可用模型目录", "可用模型目錄", "Available model catalog", "利用可能モデル一覧", "사용 가능한 모델 목록", "Catalogue des modèles disponibles", "Verfügbare Modellliste", "Catálogo de modelos", "Catálogo de modelos", "Каталог моделей", "كتالوج النماذج المتاحة"],
  ["model.fetch", "自动拉取模型", "自動拉取模型", "Fetch models", "モデルを取得", "모델 가져오기", "Récupérer les modèles", "Modelle abrufen", "Obtener modelos", "Buscar modelos", "Получить модели", "جلب النماذج"],
  ["model.fetching", "正在拉取…", "正在拉取…", "Fetching…", "取得中…", "가져오는 중…", "Récupération…", "Abruf läuft…", "Obteniendo…", "Buscando…", "Получение…", "جارٍ الجلب…"],
  ["model.defaultModel", "默认推理模型", "預設推理模型", "Default inference model", "既定の推論モデル", "기본 추론 모델", "Modèle d’inférence par défaut", "Standard-Inferenzmodell", "Modelo de inferencia predeterminado", "Modelo de inferência padrão", "Модель вывода по умолчанию", "نموذج الاستدلال الافتراضي"],
  ["model.apiKey", "API 密钥（存入系统钥匙串）", "API 密鑰（存入系統鑰匙圈）", "API key (stored in system keychain)", "API キー（システムキーチェーンに保存）", "API 키(시스템 키체인 저장)", "Clé API (trousseau système)", "API-Schlüssel (System-Schlüsselbund)", "Clave API (llavero del sistema)", "Chave API (chaveiro do sistema)", "Ключ API (системная связка ключей)", "مفتاح API (يُحفظ في سلسلة مفاتيح النظام)"],
  ["model.envName", "备用环境变量名", "備用環境變數名稱", "Fallback environment variable", "予備環境変数名", "대체 환경 변수", "Variable d’environnement de secours", "Alternative Umgebungsvariable", "Variable de entorno alternativa", "Variável de ambiente alternativa", "Резервная переменная среды", "متغير البيئة الاحتياطي"],
  ["model.save", "保存配置", "儲存設定", "Save profile", "設定を保存", "프로필 저장", "Enregistrer le profil", "Profil speichern", "Guardar perfil", "Salvar perfil", "Сохранить профиль", "حفظ الملف"],
  ["path.title", "工具调用路径", "工具呼叫路徑", "Tool invocation paths", "ツール呼び出しパス", "도구 호출 경로", "Chemins d’appel des outils", "Tool-Aufrufpfade", "Rutas de invocación", "Caminhos de chamada", "Пути вызова инструментов", "مسارات استدعاء الأدوات"],
  ["path.manual", "路径切换永不自动执行；只有用户确认后才会迁移并保留回滚回执。", "路徑切換永不自動執行；只有使用者確認後才會遷移並保留回滾回執。", "Path switching never runs automatically; migration occurs only after user confirmation and keeps a rollback receipt.", "パス切替は自動実行されません。ユーザー確認後に移行し、復元記録を残します。", "경로 전환은 자동 실행되지 않습니다. 사용자 확인 후 이전하고 롤백 기록을 보관합니다.", "Le changement de chemin n’est jamais automatique ; il exige une confirmation et conserve un reçu de retour.", "Pfadwechsel erfolgen nie automatisch; erst nach Bestätigung und mit Rückrollbeleg.", "Las rutas nunca cambian automáticamente; requieren confirmación y guardan un recibo de reversión.", "Caminhos nunca mudam automaticamente; exigem confirmação e guardam recibo de reversão.", "Пути никогда не меняются автоматически; требуется подтверждение и сохраняется откат.", "لا يتم تبديل المسارات تلقائيًا؛ بل يتطلب تأكيد المستخدم ويحتفظ بإيصال تراجع."],
  ["path.switch", "手动切换", "手動切換", "Switch manually", "手動切替", "수동 전환", "Changer manuellement", "Manuell wechseln", "Cambiar manualmente", "Alterar manualmente", "Переключить вручную", "تبديل يدوي"],
  ["audit.title", "全量结构验真与优化建议", "全量結構驗真與優化建議", "Full structural verification & optimization advice", "全構造検証と最適化提案", "전체 구조 검증 및 최적화 제안", "Vérification structurelle et conseils d’optimisation", "Vollständige Strukturprüfung & Optimierung", "Verificación estructural y recomendaciones", "Verificação estrutural e recomendações", "Полная проверка структуры и рекомендации", "تحقق هيكلي شامل واقتراحات تحسين"],
  ["audit.light", "轻量检查", "輕量檢查", "Light check", "軽量チェック", "경량 검사", "Contrôle léger", "Leichte Prüfung", "Comprobación ligera", "Verificação leve", "Лёгкая проверка", "فحص خفيف"],
  ["audit.deep", "深度验真全部", "深度驗真全部", "Deep verify all", "すべて詳細検証", "전체 심층 검증", "Tout vérifier en profondeur", "Alles tief prüfen", "Verificar todo a fondo", "Verificar tudo profundamente", "Глубоко проверить всё", "تحقق عميق من الكل"],
  ["audit.usable", "结构可用", "結構可用", "Structurally usable", "構造利用可", "구조 사용 가능", "Structure utilisable", "Struktur nutzbar", "Estructura utilizable", "Estrutura utilizável", "Структура пригодна", "البنية قابلة للاستخدام"],
  ["audit.optimize", "建议优化", "建議優化", "Optimization advised", "最適化推奨", "최적화 권장", "Optimisation conseillée", "Optimierung empfohlen", "Optimización recomendada", "Otimização recomendada", "Рекомендуется оптимизация", "يوصى بالتحسين"],
  ["audit.blocked", "当前阻塞", "目前阻塞", "Currently blocked", "現在ブロック中", "현재 차단됨", "Actuellement bloqué", "Derzeit blockiert", "Bloqueado actualmente", "Bloqueado no momento", "Заблокировано", "محظور حاليًا"],
  ["governance.title", "认证、选择与优化", "認證、選擇與優化", "Verify, select & optimize", "検証・選択・最適化", "검증, 선택 및 최적화", "Vérifier, sélectionner et optimiser", "Prüfen, auswählen & optimieren", "Verificar, seleccionar y optimizar", "Verificar, selecionar e otimizar", "Проверить, выбрать и оптимизировать", "التحقق والتحديد والتحسين"],
  ["governance.variant", "选择固定版本", "選擇固定版本", "Select pinned version", "固定バージョンを選択", "고정 버전 선택", "Sélectionner la version figée", "Fixierte Version wählen", "Seleccionar versión fijada", "Selecionar versão fixada", "Выбрать закреплённую версию", "تحديد الإصدار المثبت"],
  ["governance.license", "确认许可与使用边界", "確認許可與使用邊界", "Confirm license & usage boundary", "ライセンスと利用範囲を確認", "라이선스 및 사용 범위 확인", "Confirmer la licence et les limites", "Lizenz & Nutzung bestätigen", "Confirmar licencia y límites", "Confirmar licença e limites", "Подтвердить лицензию и границы", "تأكيد الترخيص وحدود الاستخدام"],
  ["governance.verify", "深度验真与认证", "深度驗真與認證", "Deep verification", "詳細検証", "심층 검증", "Vérification approfondie", "Tiefenprüfung", "Verificación profunda", "Verificação profunda", "Глубокая проверка", "التحقق العميق"],
  ["governance.draft", "创建并应用优化草稿", "建立並套用優化草稿", "Create and apply optimization draft", "最適化下書きを作成・適用", "최적화 초안 생성 및 적용", "Créer et appliquer un brouillon d’optimisation", "Optimierungsentwurf erstellen und anwenden", "Crear y aplicar borrador de optimización", "Criar e aplicar rascunho de otimização", "Создать и применить черновик оптимизации", "إنشاء مسودة تحسين وتطبيقها"],
  ["export.title", "导出中心", "匯出中心", "Export center", "エクスポートセンター", "내보내기 센터", "Centre d’export", "Exportzentrum", "Centro de exportación", "Central de exportação", "Центр экспорта", "مركز التصدير"],
  ["export.subtitle", "每份产物都包含来源、哈希、状态和安全排除记录。", "每份產物都包含來源、雜湊、狀態和安全排除記錄。", "Every output includes sources, hashes, states, and safety exclusions.", "各出力にはソース、ハッシュ、状態、安全除外記録が含まれます。", "모든 결과물에 출처, 해시, 상태, 안전 제외 기록이 포함됩니다.", "Chaque sortie contient sources, hachages, états et exclusions de sécurité.", "Jede Ausgabe enthält Quellen, Hashes, Status und Sicherheitsausschlüsse.", "Cada salida incluye fuentes, hashes, estados y exclusiones de seguridad.", "Cada saída inclui fontes, hashes, estados e exclusões de segurança.", "Каждый результат содержит источники, хеши, статусы и исключения безопасности.", "يتضمن كل ناتج المصادر والتجزئات والحالات واستثناءات الأمان."],
  ["export.build", "构建导出", "建立匯出", "Build export", "エクスポートを作成", "내보내기 만들기", "Créer l’export", "Export erstellen", "Crear exportación", "Criar exportação", "Создать экспорт", "إنشاء التصدير"],
  ["export.selection", "按当前选择", "依目前選擇", "Current selection", "現在の選択", "현재 선택", "Sélection actuelle", "Aktuelle Auswahl", "Selección actual", "Seleção atual", "Текущий выбор", "التحديد الحالي"],
  ["export.agentSkills", "Agent + 配合 Skills", "Agent + 配合 Skills", "Agent + companion Skills", "Agent + 連携 Skills", "Agent + 연계 Skills", "Agent + Skills associés", "Agent + zugehörige Skills", "Agent + Skills asociados", "Agent + Skills associados", "Agent + связанные Skills", "Agent + Skills المصاحبة"],
  ["export.continue", "继续选择", "繼續選擇", "Continue selecting", "選択を続ける", "계속 선택", "Continuer la sélection", "Weiter auswählen", "Seguir seleccionando", "Continuar selecionando", "Продолжить выбор", "متابعة التحديد"],
  ["export.generate", "生成导出", "產生匯出", "Generate export", "エクスポートを生成", "내보내기 생성", "Générer l’export", "Export erzeugen", "Generar exportación", "Gerar exportação", "Создать экспорт", "إنشاء التصدير"],
  ["export.exporting", "正在导出…", "正在匯出…", "Exporting…", "エクスポート中…", "내보내는 중…", "Export en cours…", "Export läuft…", "Exportando…", "Exportando…", "Экспорт…", "جارٍ التصدير…"],
  ["export.boundary", "导出边界", "匯出邊界", "Export boundaries", "エクスポート境界", "내보내기 경계", "Limites d’export", "Exportgrenzen", "Límites de exportación", "Limites de exportação", "Границы экспорта", "حدود التصدير"],
  ["export.receipts", "最近导出回执", "最近匯出回執", "Recent export receipts", "最近のエクスポート記録", "최근 내보내기 기록", "Reçus d’export récents", "Letzte Exportbelege", "Recibos recientes", "Recibos recentes", "Недавние квитанции", "إيصالات التصدير الأخيرة"]
];

const catalogs = Object.fromEntries(localeCodes.map((code) => [code, {}])) as Record<LocaleCode, Record<string, string>>;
for (const row of rows) {
  const [key, ...translations] = row;
  localeCodes.forEach((code, index) => {
    catalogs[code][key] = translations[index] ?? translations[2] ?? translations[0] ?? key;
  });
}

function normalizeLocale(value?: string | null): LocaleCode | null {
  if (!value) return null;
  const normalized = value.replace("_", "-").toLowerCase();
  if (normalized === "zh-tw" || normalized === "zh-hk" || normalized === "zh-hant") return "zh-TW";
  if (normalized.startsWith("zh")) return "zh-CN";
  const direct = localeCodes.find((code) => code.toLowerCase() === normalized);
  if (direct) return direct;
  const base = normalized.split("-")[0];
  return localeCodes.find((code) => code.toLowerCase() === base) ?? null;
}

function initialLocale(): LocaleCode {
  if (typeof window === "undefined") return "zh-CN";
  const stored = normalizeLocale(window.localStorage.getItem("lingzhan.locale.v1"));
  if (stored) return stored;
  for (const candidate of window.navigator.languages ?? [window.navigator.language]) {
    const matched = normalizeLocale(candidate);
    if (matched) return matched;
  }
  return "zh-CN";
}

export const locale = writable<LocaleCode>(initialLocale());

export function setLocale(code: LocaleCode) {
  locale.set(code);
  if (typeof window !== "undefined") window.localStorage.setItem("lingzhan.locale.v1", code);
}

export function applyDocumentLocale(code: LocaleCode) {
  if (typeof document === "undefined") return;
  const option = localeOptions.find((item) => item.code === code) ?? localeOptions[0];
  document.documentElement.lang = code;
  document.documentElement.dir = option.dir;
}

export function tr(key: string, params: MessageParams = {}, code: LocaleCode = "zh-CN"): string {
  const template = catalogs[code][key] ?? catalogs.en[key] ?? catalogs["zh-CN"][key] ?? key;
  return template.replace(/\{(\w+)\}/g, (_, name: string) => String(params[name] ?? `{${name}}`));
}

export function formatLocaleNumber(value: number, code: LocaleCode): string {
  return new Intl.NumberFormat(code).format(value);
}

export function formatLocaleDateTime(value: string | number | Date, code: LocaleCode): string {
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return String(value);
  return new Intl.DateTimeFormat(code, { dateStyle: "medium", timeStyle: "short" }).format(date);
}

export function translationCoverage(): Record<LocaleCode, { total: number; translated: number }> {
  const total = rows.length;
  return Object.fromEntries(
    localeCodes.map((code) => [code, { total, translated: Object.keys(catalogs[code]).length }])
  ) as Record<LocaleCode, { total: number; translated: number }>;
}
